-- 选择数据库
use node;

-- ALTER TABLE [:name] ADD/CHANGE COLUMN [:oldCol?] :newCol :colType;

-- 用户表
CREATE TABLE IF NOT EXISTS `node_user` (
  `id` INTEGER AUTO_INCREMENT,
  `username` VARCHAR(32) UNIQUE,
  `password` VARCHAR(128),
  `role` INTEGER,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 测试表
CREATE TABLE IF NOT EXISTS `node_test` (
  `id` INTEGER AUTO_INCREMENT,
  `name` VARCHAR(32) NULL UNIQUE,
  `status` INTEGER DEFAULT 0,
  `value` INTEGER,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

